### ISSUE TITLE
API 목록 간격 추가

### ISSUE THREAD

**Issue by heli-os** [TEAM-CLOUD-KR/datahub-front#10]

**Comment by wono9962** [comment]
https://github.com/TEAM-CLOUD-KR/datahub-front/commit/08e3dd23096c8e883d475a0c9d681312d91a277e

**Comment by heli-os** [comment]
간격 조금 좁혀주세용 mb-3 정도?

**Comment by wono9962** [comment]
https://github.com/TEAM-CLOUD-KR/datahub-front/blob/main/hyeonjeong/api/list.html
