### ISSUE TITLE
API 목록 제목 길이 제한

### ISSUE THREAD

**Issue by heli-os** [TEAM-CLOUD-KR/datahub-front#11]

**Comment by wono9962** [comment]
https://github.com/TEAM-CLOUD-KR/datahub-front/blob/main/hyeonjeong/api/list.html

**Comment by wono9962** [comment]
https://github.com/TEAM-CLOUD-KR/datahub-front/commit/2026bfc628cb6a5e4abea5f41395803927f1b536
