### ISSUE TITLE
API 목록 제공기관이 없을 때 CSS 깨짐

### ISSUE THREAD

**Issue by heli-os** [TEAM-CLOUD-KR/datahub-front#16]
![image](https://user-images.githubusercontent.com/44586666/114335972-ea147980-9b88-11eb-8f7d-5293863c9cb8.png)

**Comment by wono9962** [comment]
https://github.com/TEAM-CLOUD-KR/datahub-front/commit/97965b3f8942ea1bb1c1d36e2b5472fe75966ca5
